git:
  submodules: false

language: rust
cache: cargo
rust:
  - stable
  - beta

env:
  - UPDATE_DEPENDENCIES=false
  - UPDATE_DEPENDENCIES=true

install:
  - test $UPDATE_DEPENDENCIES != true || cargo update
  - cargo build

before_script:
  - rustup component add clippy

script:
  - ./check

  # Skip tests that require real statements from private submodule
  - cargo test --
    --skip broker_statement::ib::tests::parse_real_
    --skip broker_statement::open_broker::tests::parse_real
    --skip tax_statement::statement::parser::tests::parse_real