[package]
name = "investments"
version = "0.1.0"
edition = "2018"
authors = ["Dmitry Konishchev"]

[dependencies]
ansi_term = "*"
chrono = "*"
chrono-tz = "*"
cast = "*"
clap = "*"
csv = "*"
diesel = { version = "*", features = ["sqlite", "chrono"] }
diesel-derive-enum = { version = "*", features = ["sqlite"] }
diesel_migrations = "*"
easy-logging = "*"
encoding_rs = "*"
indoc = "*"
lazy_static = "*"
log = "0.4"
num-traits = "*"
prettytable-rs = "0.8"
regex = "*"
reqwest = "*"
rust_decimal = "*"
rust_decimal_macros = "*"
separator = "*"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "*"
shellexpand = "*"

# The latest published version (0.2.1) has bugs and abandoned, so using git
[dependencies.serde-xml-rs]
git = "https://github.com/RReverser/serde-xml-rs.git"
#rev = "551c78d155cac89815e28d0f36a87029a8bf2a62"

[dev-dependencies]
matches = "*"
mockito = "*"
rstest = "0.2"
tempfile = "*"