[package]
name = "investment-tools"
version = "0.1.0"
authors = ["Dmitry Konishchev"]

[dependencies]
chrono = "*"
clap = "*"
csv = "*"
diesel = { version = "*", features = ["sqlite", "chrono"] }
diesel_migrations = "*"
easy-logging = "*"
indoc = "*"
lazy_static = "*"
log = "*"
matches = "*"
mockito = "*"
num-traits = "*"
regex = "*"
reqwest = "*"
rust_decimal = "*"
serde = "*"
serde_derive = "*"
serde-xml-rs = "*"
serde_yaml = "*"
shellexpand = "*"
tempfile = "*"