[package]
name = "investment-analyzer"
version = "0.1.0"
authors = ["Dmitry Konishchev"]

[dependencies]
bigdecimal = "*"
chrono = "*"
csv = "*"
easy-logging = "*"
indoc = "*"
lazy_static = "*"
log = "*"
mockito = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde-xml-rs = "*"