[package]
name = "investments"
version = "0.1.0"
authors = ["Dmitry Konishchev"]

[dependencies]
chrono = "*"
chrono-tz = "*"
clap = "*"
csv = "*"
diesel = { version = "*", features = ["sqlite", "chrono"] }
diesel_migrations = "*"
easy-logging = "*"
encoding_rs = "*"
indoc = "*"
lazy_static = "*"
log = "0.4"
matches = "*"
mockito = "*"
num-traits = "*"
prettytable-rs = "0.8"
regex = "*"
reqwest = "*"
rust_decimal = "*"
separator = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
shellexpand = "*"
tempfile = "*"

[dependencies.serde-xml-rs]
git = "https://github.com/RReverser/serde-xml-rs.git"
#rev = "551c78d155cac89815e28d0f36a87029a8bf2a62"