[package]
name = "investments"
version = "0.1.0"
edition = "2018"
authors = ["Dmitry Konishchev"]
default-run = "investments"

[[bin]]
name = "investments"
path = "src/bin/investments/mod.rs"

[[bin]]
name = "tax-statement-parser"
path = "src/bin/tax_statement_parser.rs"

[dependencies]
ansi_term = "*"
calamine = "*"
chrono = "*"
chrono-tz = "*"
cast = "*"
clap = "*"
csv = "*"
diesel = { version = "*", features = ["sqlite", "chrono"] }
diesel-derive-enum = { version = "*", features = ["sqlite"] }
diesel_migrations = "*"
easy-logging = "*"
encoding_rs = "*"
indoc = "*"
lazy_static = "*"
log = "*"
maplit = "*"
matches = "*"
num-traits = "*"
prettytable-rs = "*"
regex = "*"
reqwest = "*"
rust_decimal = "*"
rust_decimal_macros = "*"
separator = "*"
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
serde-xml-rs = "*"
shellexpand = "*"
static_table_derive = { path = "src/formatting/static_table_derive" }
xls_table_derive = { path = "src/xls/xls_table_derive" }

[dev-dependencies]
mockito = "*"
rstest = "*"
tempfile = "*"
url = "*"
