[package]
name = "investment-analyzer"
version = "0.1.0"
authors = ["Dmitry Konishchev"]

[dependencies]
bigdecimal = "*"
chrono = "*"
csv = "*"
diesel = { version = "*", features = ["sqlite", "chrono"] }
diesel_migrations = "*"
easy-logging = "*"
indoc = "*"
lazy_static = "*"
log = "*"
matches = "*"
mockito = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde-xml-rs = "*"
tempfile = "*"