# FIXME

[package]
name = "static_table_derive"
version = "0.1.0"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "*"
syn = "*"
quote = "*"