[package]
name = "xls_table_derive"
version = "0.1.0"
edition = "2018"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
darling = ">= 0.10"
proc-macro2 = ">= 1"
quote = ">= 1"
syn = ">= 1"