[package]
name = "static_table_derive"
version = "0.1.0"
edition = "2018"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
darling = "*"
proc-macro2 = "*"
quote = "*"
syn = "*"